  # Use the latest 2.1 version of CircleCI pipeline process engine.
  # See: https://circleci.com/docs/2.0/configuration-reference
  version: 2.1
  orbs:
    aws-eks: circleci/aws-eks@2.2.0
    kubernetes: circleci/kubernetes@1.3  

  jobs: 
    create-dd-monitor:
      docker:
        - image: 'cimg/python:3.10'
      parameters:
        cluster-name:
          description: |
            Cluster Name
          type: string
        aws-region:
          description: |
            AWS Region
          type: string        
      steps:
        - run:
            name: Build doc
            command: |
              echo 
              git clone https://github.com/shankarcit/eks-deploy.git ~/deployment/configs/
              sed -i "s/latest/${CIRCLE_WORKFLOW_ID}/g" ~/deployment/configs/deployment/demo-app-deployment.yaml
     
        - aws-eks/update-kubeconfig-with-authenticator:
            cluster-name: << parameters.cluster-name >>
            aws-region: << parameters.aws-region >>
            install-kubectl: true
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/datadog/cluster-agent-rbac.yaml
            resource-name: ClusterRole/datadog-cluster-agent
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/datadog/datadog-rbac.yaml
            resource-name: ClusterRole/datadog-agent
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/datadog/dca-secret.yaml
            resource-name: secret/datadog-auth-token
        - kubernetes/create-or-update-resource:
            get-rollout-status: true
            resource-file-path: ~/deployment/configs/datadog/datadog-cluster-agent.yaml
            resource-name: deployment/datadog-cluster-agent          
        - kubernetes/create-or-update-resource:
            get-rollout-status: true
            resource-file-path: ~/deployment/configs/datadog/datadog-agent.yaml
            resource-name: DaemonSet/datadog-agent
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/state-metrics/cluster-role.yaml
            resource-name: ClusterRole/kube-state-metrics
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/state-metrics/cluster-role-binding.yaml
            resource-name: ClusterRoleBinding/kube-state-metrics
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/state-metrics/service-account.yaml
            resource-name: ServiceAccount/kube-state-metrics                    
        - kubernetes/create-or-update-resource:
            get-rollout-status: true
            resource-file-path: ~/deployment/configs/state-metrics/deployment.yaml
            resource-name: deployment/kube-state-metrics
        - kubernetes/create-or-update-resource:
            get-rollout-status: false
            resource-file-path: ~/deployment/configs/state-metrics/service.yaml
            resource-name: Service/kube-state-metrics

  # Invoke jobs via workflows
  # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
  workflows:
    deploy-monitor-agent:
      jobs:
        - create-dd-monitor:
            cluster-name: k8s-dev-abc-demo
            aws-region: ap-northeast-1
            filters:
              branches:
                only: develop
        - create-dd-monitor:
            cluster-name: k8s-sqa-abc-demo
            aws-region: ap-northeast-1
            filters:
              branches:
                only: sqa
